apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-webhook-joker.fullname" . }}
  labels:
    {{- include "cert-manager-webhook-joker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "cert-manager-webhook-joker.selectorLabels" . | nindent 4 }}
